### ISSUE TITLE
Python errors when running docker-make

### ISSUE THREAD

**Issue by Dids** [CtripCloud/docker-make#11] opened 2017-05-12 14:59 UTC
On macOS Sierra (10.12.4), python 2.7.10 and latest docker-make from pip.

```sh
> docker-make --no-push
WARNING dmake.template_args(44) 2017-05-12 17:59:31,850 failed to run %s: %s
WARNING dmake.template_args(44) 2017-05-12 17:59:31,866 failed to run %s: %s
INFO dmake.template_args(44) 2017-05-12 17:59:31,883 failed to run %s: %s
WARNING dmake.build(60) 2017-05-12 17:59:31,883 invalid label template: org.label-schema.vcs-ref={fcommitid}
WARNING dmake.build(60) 2017-05-12 17:59:31,883 invalid label template: org.label-schema.vcs-ref={fcommitid}
WARNING dmake.build(60) 2017-05-12 17:59:31,883 invalid label template: org.label-schema.vcs-ref={fcommitid}
WARNING dmake.build(60) 2017-05-12 17:59:31,883 invalid label template: org.label-schema.vcs-ref={fcommitid}
WARNING dmake.build(60) 2017-05-12 17:59:31,883 invalid label template: org.label-schema.vcs-ref={fcommitid}
INFO dmake.build(145) 2017-05-12 17:59:31,883 alpine-3.5: building
ERROR docker-make(86) 2017-05-12 17:59:32,002 failed to build alpine-3.5
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/dmake/cli.py", line 80, in _main
    build.build()
  File "/Library/Python/2.7/site-packages/dmake/build.py", line 86, in build
    self.non_labeled_image = self._build()
  File "/Library/Python/2.7/site-packages/dmake/build.py", line 186, in _build
    image_id = self._do_build(params)
  File "/Library/Python/2.7/site-packages/dmake/build.py", line 217, in _do_build
    ret = json.loads(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 40 - 122)
```

**Comment by Dids** [comment] 2017-05-12 15:01
Ah, guess this is related to #8. Any workarounds yet?

**Comment by jizhilong** [comment] 2017-05-12 15:07
@Dids  this is the same issue  reported in #8 , the patch to `dmake/build.py` in #8 should be able to fix it, you can apply it to your local installation as a work around.Since there are other corner cases not covered by #8 , the PR is not merged for now, but I'll improve the fix as soon as possible.

**Comment by Dids** [comment] 2017-05-12 15:10
@jizhilong Thanks! I'm assuming aliasing the Docker run command would work fine too?

**Comment by jizhilong** [comment] 2017-05-12 15:13
Did you mean you're running `docker-make` via alias to a `docker run` command?In that case, applying the patch would be difficult, since you have to build a new docker image for `docker-make` with the patch applied.

**Comment by Dids** [comment] 2017-05-12 15:15
@jizhilong No no, I'm using the Python version, but I'm assuming if I uninstall that and switch to the alias, it'll work fine?

**Comment by Dids** [comment] 2017-05-12 15:18
@jizhilong Looks like the Docker run alias is leaving behind containers for every build. Is this on purpose, or should I create a separate issue for this?
They're not visible with `docker ps`, but do show up with `docker ps -a`.

**Comment by jizhilong** [comment] 2017-05-12 15:18
No, it wont.But after a proper fix applied to the branch master, and the docker image updated, it should work then.

**Comment by jizhilong** [comment] 2017-05-12 15:19
Did you add the`--rm` option to `docker run`?

**Comment by Dids** [comment] 2017-05-12 15:21
Yes, since I directly copied it from the readme.

**Comment by jizhilong** [comment] 2017-05-12 15:23
Could you paste the output of `docker ps -a`, especially the part you think should not appear?

**Comment by Dids** [comment] 2017-05-12 17:56
After building with `--no-push`, all of these are left behind:
```
> docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
3a808cc249d1        c7de72a32c97        "/bin/sh -c '#(nop..."   About a minute ago   Created                                 eager_allen
bd217aa4bb67        5252e743a66d        "/bin/sh -c '#(nop..."   About a minute ago   Created                                 focused_goldwasser
945f7eb13a44        9be529c49ca4        "/bin/sh -c '#(nop..."   About a minute ago   Created                                 brave_easley
8ef00e1d0a84        53b0b3a2a123        "/bin/sh -c '#(nop..."   About a minute ago   Created                                 laughing_panini
05b9568345ee        d386786c09e8        "/bin/sh -c '#(nop..."   About a minute ago   Created                                 tender_meitner
```

**Comment by Dids** [comment] 2017-05-12 18:26
Triple confirmed that `docker-make` is what generates them, and they're not just per build either (perhaps per layer, unless there's something else going on?.

I forcefully removed all local containers and images, then ran `docker-make --no-push` again, and there were left behind:
```
> docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                          PORTS               NAMES
2ae3cfef2a3a        2b0cf65f05d6        "/bin/sh -c '#(nop..."   About a minute ago   Created                                             confident_stonebraker
da55aaae57b0        a0624194fd40        "/bin/sh -c '#(nop..."   About a minute ago   Created                                             youthful_kowalevski
4221a6bbed22        a0624194fd40        "/bin/sh -c '#(nop..."   About a minute ago   Created                                             romantic_khorana
aac2f716a125        8c577cdb7b5c        "/bin/sh -c '#(nop..."   About a minute ago   Created                                             wizardly_cori
9df0eb3c6b3d        724b0c96c20e        "/bin/sh -c '#(nop..."   About a minute ago   Created                                             awesome_noyce
655faeddbb1d        bbe556705be1        "/bin/sh -c 'apt-g..."   About a minute ago   Exited (0) About a minute ago                       eager_dijkstra
186e738a57ca        49c5d66b9d27        "/bin/sh -c '#(nop..."   About a minute ago   Created                                             infallible_edison
9c0bcc77c8cf        f7b3f317ec73        "/bin/sh -c '#(nop..."   About a minute ago   Created                                             musing_kirch
365ce2a05db0        f4381ccfd652        "/bin/sh -c '#(nop..."   2 minutes ago        Created                                             hungry_mcclintock
92872fe79d64        edb986eca53d        "/bin/sh -c '#(nop..."   2 minutes ago        Created                                             quirky_curran
11bc1bf364a0        edb986eca53d        "/bin/sh -c '#(nop..."   2 minutes ago        Created                                             angry_lewin
4d6a1e9635f9        e6c222d9256e        "/bin/sh -c '#(nop..."   2 minutes ago        Created                                             optimistic_jones
b8779e3b1941        46cde8304dbb        "/bin/sh -c '#(nop..."   2 minutes ago        Created                                             hardcore_lalande
ce499691bcb7        b71180242435        "/bin/sh -c 'apt-g..."   2 minutes ago        Exited (0) 2 minutes ago                            focused_meninsky
f0e2e10d5f39        75619f7d1fc1        "/bin/sh -c '#(nop..."   2 minutes ago        Created                                             elegant_pare
fab3e7c1b8b9        302fa07d8117        "/bin/sh -c '#(nop..."   2 minutes ago        Created                                             sharp_snyder
7b4898c6089b        7b060b4ce06f        "/bin/sh -c '#(nop..."   3 minutes ago        Created                                             dazzling_jepsen
48d8f1da3dd0        7cfc79280a1e        "/bin/sh -c '#(nop..."   3 minutes ago        Created                                             gracious_galileo
44e11853a0c2        02674b9cb179        "/bin/sh -c '#(nop..."   3 minutes ago        Created                                             loving_beaver
```

Note that if I remove these, then run the command again, they don't get generated, unless I change something (which makes sense).

**Comment by jizhilong** [comment] 2017-05-13 02:15
What you described is exactly how docker build images.Docker engine will create a intermediate container for each image level(a instruction in you Dockerfile).These containers wont get removed by default after each image building.

> Note that if I remove these, then run the command again, they don't get generated, unless I change something (which makes sense).

that is because docker has a caching mechanism, there is a [official document ](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#build-cache) talking about how build-cache works.

**Comment by Dids** [comment] 2017-05-13 06:04
@jizhilong I know how layer caching works, yes, but this is that it, since they only show up in both `docker ps -a` and in [Kitematic](https://kitematic.com) when using Docker Make. Docker stores the layers are images, not containers, so the ones leftover from Docker Make don't make any sense. If I build the images in `.docker-make.yml` by hand, they _do not_ leave behind containers.

**Comment by Dids** [comment] 2017-05-13 10:39
Still trying to find what's actually causing the issue, but basically running `docker build -rm` will remove intermediate containers _if_ they succeeded.

**Comment by Dids** [comment] 2017-05-13 10:49
Another option is that the intermediate containers are being marked as unsuccessful (even though they succeed), which is why they get left behind. Could this line potentially return an error/exit code that's not zero?
```
INFO dmake.template_args(44) 2017-05-13 10:46:12,232 failed to run %s: %s
```

**Comment by Dids** [comment] 2017-05-13 15:38
If I use `--dry-run`, then run the build commands myself, they build fine and don't leave behind any intermediate containers. Adding `-rm` to the generated build command should ensure the intermediate containers are removed, if they were successful.
Still not sure _why_ dmake is not working as expected, since running the build commands manually works. To reiterate, using `docker build` without specifying `-rm` should still remove these extra containers, and it does, unless built with Docker Make.

**Comment by jizhilong** [comment] 2017-05-15 02:40
@Dids I think I got the root cause now: `docker-make`  uses `docker-py` to make API requests to `docker-engine`, and there are many options for the `docker build` API, `docker-make` just use the default value of `docker-py` without giving the ability to the end user to override these option values in `.docker-make.yml`.The default value of option `rm` of the `build` API in `docker-py` is `False`([ref code](https://github.com/docker/docker-py/blob/master/docker/api/build.py#L17)), so `docker-make` will not clean up any intermediate containers in a build.

**Comment by jizhilong** [comment] 2017-05-15 02:43
The ultimate fix to this issue is to provide the ability to override the build options in `.docker-make.yml` instead of just using the defaults of `docker-py`

**Comment by Dids** [comment] 2017-05-15 05:53
From the source of that file:
```
rm (bool): Remove intermediate containers. The ``docker build``
                command now defaults to ``--rm=true``, but we have kept the old
                default of `False` to preserve backward compatibility
```
Looks like their "compatibility" isn't compatible with the new default, heh.

**Comment by Dids** [comment] 2017-05-15 05:55
Since the root issue is technically in `docker-py`, I opened an issue about it here:
https://github.com/docker/docker-py/issues/1609

If that doesn't go anywhere, I can try and help with implementing the build override arguments for Docker Make.

**Comment by jizhilong** [comment] 2017-05-15 06:14
@Dids It would be great if you can help to implement the feature for overriding arguments in `.docker-make.yml`

**Closed as completed** 2017-06-05 14:07 UTC
